[package]
name = "generator"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.98"
bitflags = "2.9.1"
dotenvy = "0.15.7"
indicatif = "0.18.0"
postgres = "0.19.10"
rayon = "1.10.0"
thousands = "0.2.0"
