// auto-generated file - do not change manually. See generator/build.rs for details

export const TAG = {
  SYM_H: { key: 'SYM_H', label: 'sym-h', bit: 1n << 0n, category: 'Symmetry' },
  SYM_V: { key: 'SYM_V', label: 'sym-v', bit: 1n << 1n, category: 'Symmetry' },
  SYM_DIAG: { key: 'SYM_DIAG', label: 'sym-diag', bit: 1n << 2n, category: 'Symmetry' },
  SYM_ANTI_DIAG: { key: 'SYM_ANTI_DIAG', label: 'sym-anti-diag', bit: 1n << 3n, category: 'Symmetry' },
  SYM: { key: 'SYM', label: 'sym', bit: 1n << 4n, category: 'Symmetry' },
  SYM_ALL: { key: 'SYM_ALL', label: 'sym-all', bit: 1n << 5n, category: 'Symmetry' },
  SYM_FOUR_FOLD_ROTATION: { key: 'SYM_FOUR_FOLD_ROTATION', label: 'four-fold-rotation', bit: 1n << 6n, category: 'Symmetry' },
  BORDERS_TOP_BORDER_STRICT: { key: 'BORDERS_TOP_BORDER_STRICT', label: 'top-border-strict', bit: 1n << 7n, category: 'Border' },
  BORDERS_TOP_BORDER_MODERATE: { key: 'BORDERS_TOP_BORDER_MODERATE', label: 'top-border-moderate', bit: 1n << 8n, category: 'Border' },
  BORDERS_BOTTOM_BORDER_STRICT: { key: 'BORDERS_BOTTOM_BORDER_STRICT', label: 'bottom-border-strict', bit: 1n << 9n, category: 'Border' },
  BORDERS_BOTTOM_BORDER_MODERATE: { key: 'BORDERS_BOTTOM_BORDER_MODERATE', label: 'bottom-border-moderate', bit: 1n << 10n, category: 'Border' },
  BORDERS_LEFT_BORDER_STRICT: { key: 'BORDERS_LEFT_BORDER_STRICT', label: 'left-border-strict', bit: 1n << 11n, category: 'Border' },
  BORDERS_LEFT_BORDER_MODERATE: { key: 'BORDERS_LEFT_BORDER_MODERATE', label: 'left-border-moderate', bit: 1n << 12n, category: 'Border' },
  BORDERS_RIGHT_BORDER_STRICT: { key: 'BORDERS_RIGHT_BORDER_STRICT', label: 'right-border-strict', bit: 1n << 13n, category: 'Border' },
  BORDERS_RIGHT_BORDER_MODERATE: { key: 'BORDERS_RIGHT_BORDER_MODERATE', label: 'right-border-moderate', bit: 1n << 14n, category: 'Border' },
  BORDERS_FULL_BORDER_MODERATE: { key: 'BORDERS_FULL_BORDER_MODERATE', label: 'full-border-moderate', bit: 1n << 15n, category: 'Border' },
  BORDERS_FULL_BORDER_STRICT: { key: 'BORDERS_FULL_BORDER_STRICT', label: 'full-border-strict', bit: 1n << 16n, category: 'Border' },
  WEIGHT_CENTER_HEAVY: { key: 'WEIGHT_CENTER_HEAVY', label: 'center-heavy', bit: 1n << 17n, category: 'Weight Distribution' },
  WEIGHT_CENTER_EMPTY: { key: 'WEIGHT_CENTER_EMPTY', label: 'center-empty', bit: 1n << 18n, category: 'Weight Distribution' },
  WEIGHT_EDGE_HEAVY: { key: 'WEIGHT_EDGE_HEAVY', label: 'edge-heavy', bit: 1n << 19n, category: 'Weight Distribution' },
  WEIGHT_TOP_HEAVY: { key: 'WEIGHT_TOP_HEAVY', label: 'top-heavy', bit: 1n << 20n, category: 'Weight Distribution' },
  WEIGHT_BOTTOM_HEAVY: { key: 'WEIGHT_BOTTOM_HEAVY', label: 'bottom-heavy', bit: 1n << 21n, category: 'Weight Distribution' },
  WEIGHT_LEFT_HEAVY: { key: 'WEIGHT_LEFT_HEAVY', label: 'left-heavy', bit: 1n << 22n, category: 'Weight Distribution' },
  WEIGHT_RIGHT_HEAVY: { key: 'WEIGHT_RIGHT_HEAVY', label: 'right-heavy', bit: 1n << 23n, category: 'Weight Distribution' },
  WEIGHT_TOP_LEFT_HEAVY: { key: 'WEIGHT_TOP_LEFT_HEAVY', label: 'top-left-heavy', bit: 1n << 24n, category: 'Weight Distribution' },
  WEIGHT_TOP_RIGHT_HEAVY: { key: 'WEIGHT_TOP_RIGHT_HEAVY', label: 'top-right-heavy', bit: 1n << 25n, category: 'Weight Distribution' },
  WEIGHT_BOTTOM_LEFT_HEAVY: { key: 'WEIGHT_BOTTOM_LEFT_HEAVY', label: 'bottom-left-heavy', bit: 1n << 26n, category: 'Weight Distribution' },
  WEIGHT_BOTTOM_RIGHT_HEAVY: { key: 'WEIGHT_BOTTOM_RIGHT_HEAVY', label: 'bottom-right-heavy', bit: 1n << 27n, category: 'Weight Distribution' },
  SHAPE_CROSS: { key: 'SHAPE_CROSS', label: 'shape-cross', bit: 1n << 28n, category: 'Shape' },
  SHAPE_ALL_CORNERS: { key: 'SHAPE_ALL_CORNERS', label: 'shape-all-corners', bit: 1n << 29n, category: 'Shape' },
  SHAPE_L: { key: 'SHAPE_L', label: 'shape-l', bit: 1n << 30n, category: 'Shape' },
  SHAPE_T: { key: 'SHAPE_T', label: 'shape-t', bit: 1n << 31n, category: 'Shape' },
  SHAPE_RING: { key: 'SHAPE_RING', label: 'shape-ring', bit: 1n << 32n, category: 'Shape' },
  SHAPE_X: { key: 'SHAPE_X', label: 'shape-x', bit: 1n << 33n, category: 'Shape' },
  SHAPE_ARROW: { key: 'SHAPE_ARROW', label: 'shape-arrow', bit: 1n << 34n, category: 'Shape' },
  SHAPE_H: { key: 'SHAPE_H', label: 'shape-h', bit: 1n << 35n, category: 'Shape' },
  GENERAL_HORIZONTAL_LINE: { key: 'GENERAL_HORIZONTAL_LINE', label: 'horizontal-line', bit: 1n << 36n, category: 'Basic Elements' },
  GENERAL_VERTICAL_LINE: { key: 'GENERAL_VERTICAL_LINE', label: 'vertical-line', bit: 1n << 37n, category: 'Basic Elements' },
  GENERAL_ISOLATED_PIXELS: { key: 'GENERAL_ISOLATED_PIXELS', label: 'isolated-pixels', bit: 1n << 38n, category: 'Basic Elements' },
} as const;

export const TAGS = Object.values(TAG) as readonly Tag[];

export const BIT = {
  SYM_H: 1n << 0n,
  SYM_V: 1n << 1n,
  SYM_DIAG: 1n << 2n,
  SYM_ANTI_DIAG: 1n << 3n,
  SYM: 1n << 4n,
  SYM_ALL: 1n << 5n,
  SYM_FOUR_FOLD_ROTATION: 1n << 6n,
  BORDERS_TOP_BORDER_STRICT: 1n << 7n,
  BORDERS_TOP_BORDER_MODERATE: 1n << 8n,
  BORDERS_BOTTOM_BORDER_STRICT: 1n << 9n,
  BORDERS_BOTTOM_BORDER_MODERATE: 1n << 10n,
  BORDERS_LEFT_BORDER_STRICT: 1n << 11n,
  BORDERS_LEFT_BORDER_MODERATE: 1n << 12n,
  BORDERS_RIGHT_BORDER_STRICT: 1n << 13n,
  BORDERS_RIGHT_BORDER_MODERATE: 1n << 14n,
  BORDERS_FULL_BORDER_MODERATE: 1n << 15n,
  BORDERS_FULL_BORDER_STRICT: 1n << 16n,
  WEIGHT_CENTER_HEAVY: 1n << 17n,
  WEIGHT_CENTER_EMPTY: 1n << 18n,
  WEIGHT_EDGE_HEAVY: 1n << 19n,
  WEIGHT_TOP_HEAVY: 1n << 20n,
  WEIGHT_BOTTOM_HEAVY: 1n << 21n,
  WEIGHT_LEFT_HEAVY: 1n << 22n,
  WEIGHT_RIGHT_HEAVY: 1n << 23n,
  WEIGHT_TOP_LEFT_HEAVY: 1n << 24n,
  WEIGHT_TOP_RIGHT_HEAVY: 1n << 25n,
  WEIGHT_BOTTOM_LEFT_HEAVY: 1n << 26n,
  WEIGHT_BOTTOM_RIGHT_HEAVY: 1n << 27n,
  SHAPE_CROSS: 1n << 28n,
  SHAPE_ALL_CORNERS: 1n << 29n,
  SHAPE_L: 1n << 30n,
  SHAPE_T: 1n << 31n,
  SHAPE_RING: 1n << 32n,
  SHAPE_X: 1n << 33n,
  SHAPE_ARROW: 1n << 34n,
  SHAPE_H: 1n << 35n,
  GENERAL_HORIZONTAL_LINE: 1n << 36n,
  GENERAL_VERTICAL_LINE: 1n << 37n,
  GENERAL_ISOLATED_PIXELS: 1n << 38n,
} as const;

export type TagKey = keyof typeof TAG;

export type Tag = typeof TAG[TagKey];

export const isTagKey = (k: string): k is TagKey => k in TAG;

