export const TagBits = {
  SYM_H: 1n << 0n,
  SYM_V: 1n << 1n,
  SYM_DIAG: 1n << 2n,
  SYM_ANTI_DIAG: 1n << 3n,
  SYM: 1n << 4n,
  SYM_ALL: 1n << 5n,
  FOUR_FOLD_ROTATION: 1n << 6n,
  TOP_BORDER_STRICT: 1n << 7n,
  TOP_BORDER_MODERATE: 1n << 8n,
  BOTTOM_BORDER_STRICT: 1n << 9n,
  BOTTOM_BORDER_MODERATE: 1n << 10n,
  LEFT_BORDER_STRICT: 1n << 11n,
  LEFT_BORDER_MODERATE: 1n << 12n,
  RIGHT_BORDER_STRICT: 1n << 13n,
  RIGHT_BORDER_MODERATE: 1n << 14n,
  FULL_BORDER_MODERATE: 1n << 15n,
  FULL_BORDER_STRICT: 1n << 16n,
  CENTER_HEAVY: 1n << 17n,
  CENTER_EMPTY: 1n << 18n,
  EDGE_HEAVY: 1n << 19n,
  TOP_HEAVY: 1n << 20n,
  BOTTOM_HEAVY: 1n << 21n,
  LEFT_HEAVY: 1n << 22n,
  RIGHT_HEAVY: 1n << 23n,
  TOP_LEFT_HEAVY: 1n << 24n,
  TOP_RIGHT_HEAVY: 1n << 25n,
  BOTTOM_LEFT_HEAVY: 1n << 26n,
  BOTTOM_RIGHT_HEAVY: 1n << 27n,
  SHAPE_CROSS: 1n << 28n,
  SHAPE_ALL_CORNERS: 1n << 29n,
  SHAPE_L: 1n << 30n,
  SHAPE_T: 1n << 31n,
  SHAPE_RING: 1n << 32n,
  SHAPE_X: 1n << 33n,
  SHAPE_ARROW: 1n << 34n,
  SHAPE_H: 1n << 35n,
  HORIZONTAL_LINE: 1n << 36n,
  VERTICAL_LINE: 1n << 37n,
  ISOLATED_PIXELS: 1n << 38n,
} as const;

export const TagLabels = {
   SYM_H: 'sym-h', 
   SYM_V: 'sym-v', 
   SYM_DIAG: 'sym-diag', 
   SYM_ANTI_DIAG: 'sym-anti-diag', 
   SYM: 'sym', 
   SYM_ALL: 'sym-all', 
   FOUR_FOLD_ROTATION: 'four-fold-rotation', 
   TOP_BORDER_STRICT: 'top-border-strict', 
   TOP_BORDER_MODERATE: 'top-border-moderate', 
   BOTTOM_BORDER_STRICT: 'bottom-border-strict', 
   BOTTOM_BORDER_MODERATE: 'bottom-border-moderate', 
   LEFT_BORDER_STRICT: 'left-border-strict', 
   LEFT_BORDER_MODERATE: 'left-border-moderate', 
   RIGHT_BORDER_STRICT: 'right-border-strict', 
   RIGHT_BORDER_MODERATE: 'right-border-moderate', 
   FULL_BORDER_MODERATE: 'full-border-moderate', 
   FULL_BORDER_STRICT: 'full-border-strict', 
   CENTER_HEAVY: 'center-heavy', 
   CENTER_EMPTY: 'center-empty', 
   EDGE_HEAVY: 'edge-heavy', 
   TOP_HEAVY: 'top-heavy', 
   BOTTOM_HEAVY: 'bottom-heavy', 
   LEFT_HEAVY: 'left-heavy', 
   RIGHT_HEAVY: 'right-heavy', 
   TOP_LEFT_HEAVY: 'top-left-heavy', 
   TOP_RIGHT_HEAVY: 'top-right-heavy', 
   BOTTOM_LEFT_HEAVY: 'bottom-left-heavy', 
   BOTTOM_RIGHT_HEAVY: 'bottom-right-heavy', 
   SHAPE_CROSS: 'shape-cross', 
   SHAPE_ALL_CORNERS: 'shape-all-corners', 
   SHAPE_L: 'shape-l', 
   SHAPE_T: 'shape-t', 
   SHAPE_RING: 'shape-ring', 
   SHAPE_X: 'shape-x', 
   SHAPE_ARROW: 'shape-arrow', 
   SHAPE_H: 'shape-h', 
   HORIZONTAL_LINE: 'horizontal-line', 
   VERTICAL_LINE: 'vertical-line', 
   ISOLATED_PIXELS: 'isolated-pixels', 
} satisfies Record<keyof typeof TagBits, string>;

export type TagMask = bigint;
